Run unit tests in the CI
PropelAuth/rust pull request #37
Opened 2024-04-06 12:53 UTC by edbo

* Fixes test compilation issue in token.rs
* Adds `cargo test` to CI
* Disables doc tests because they're not compiling

2024-04-06 13:06 UTC, edbo commented
Successful test run here:

https://github.com/ShiftControl-io/rust/actions/runs/8581278439

2024-04-09 19:47 UTC, mrmauer commented
Hey @edbo,
Thanks for the PR! The added CI task looks like a no brainer to me. The only thing here is that the testing fixes (ie ignoring doctests and adding the missing fields for a few tests) are all addressed now on main. Can you update your fork/branch first before we move forward?

2024-04-09 20:41 UTC, edbo commented
@mrmauer Thanks for reviewing.

I've rebased against your main branch now so hopefully this is good to merge now.

2024-04-09 20:49 UTC, mrmauer requested changes
Just need to remove redundant declarations of `properties` in the tests module.

2024-04-09 20:49 UTC, mrmauer commented on src/propelauth/token.rs
> +            properties: None,
`properties` is also declared on line 204 below. Can you remove this and the other 2 instances of adding `properties` to a `User` below?

2024-04-09 20:54 UTC, edbo commented
@mrmauer Thanks! Sorry didn't spot that, running tests passes locally now.

2024-04-09 21:14 UTC, mrmauer approved these changes
LGTM! Thanks for the PR.

2024-04-09 21:37 UTC, merged